export function getAkiTradeControlPlaneLandingPage() {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#081a2a" />
    <title>AkiTrade Control Plane</title>
    <style>
      :root { color-scheme: dark; --ink:#081a2a; --line:#274760; --text:#f5f8fc; --muted:#a8b8c8; --teal:#2dd4bf; --amber:#fbbf24; --red:#fb7185; }
      * { box-sizing: border-box; } body { margin:0; min-height:100vh; background:radial-gradient(circle at 85% 0%, #174878 0%, transparent 30%), var(--ink); color:var(--text); font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; }
      main { width:min(1040px, calc(100% - 40px)); margin:0 auto; padding:56px 0 72px; } .top { display:flex; align-items:flex-start; justify-content:space-between; gap:24px; } .brand { display:flex; align-items:center; gap:14px; } .mark { display:grid; place-items:center; width:48px; height:48px; border-radius:15px; background:linear-gradient(145deg,#497df0,#285bb8); font-size:13px; font-weight:900; letter-spacing:.1em; } h1 { margin:0; font-size:clamp(26px,5vw,42px); line-height:1.05; letter-spacing:-.045em; } .subtitle { margin:12px 0 0; color:var(--muted); max-width:620px; line-height:1.55; } .badge { display:inline-flex; align-items:center; gap:8px; margin-top:6px; padding:10px 12px; border:1px solid var(--line); border-radius:999px; color:#d4e5f8; font-size:12px; font-weight:800; } .dot { width:8px; height:8px; border-radius:50%; background:var(--teal); box-shadow:0 0 18px var(--teal); } .grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:16px; margin-top:36px; } .card { min-height:218px; padding:24px; border:1px solid var(--line); border-radius:22px; background:linear-gradient(145deg,rgba(20,55,85,.96),rgba(12,36,58,.96)); box-shadow:0 18px 38px rgba(0,0,0,.16); } .label { margin:0; color:var(--muted); font-size:12px; font-weight:800; letter-spacing:.08em; } .value { margin:16px 0 0; font-size:28px; line-height:1.08; font-weight:900; letter-spacing:-.03em; } .detail { margin:10px 0 0; color:var(--muted); font-size:14px; line-height:1.5; } .status { display:inline-flex; align-items:center; gap:8px; margin-top:20px; padding:8px 10px; border-radius:999px; background:rgba(45,212,191,.1); color:#7ff6e0; font-size:12px; font-weight:800; } .status.warning { background:rgba(251,191,36,.1); color:#fde68a; } .status.error { background:rgba(251,113,133,.12); color:#fda4af; } .foot { display:flex; justify-content:space-between; gap:16px; margin-top:20px; color:var(--muted); font-size:12px; } a { color:#a9caff; } @media(max-width:640px){ main { width:min(100% - 28px,1040px); padding-top:32px; } .top { display:block; } .badge { margin-top:20px; } .grid { grid-template-columns:1fr; margin-top:24px; } .foot { display:block; } .foot p+p { margin-top:10px; } }
    </style>
  </head>
  <body>
    <main>
      <section class="top">
        <div><div class="brand"><div class="mark">AKI</div><div><h1>AkiTrade Control Plane</h1><p class="subtitle">Exness Auto Trader is online. This public dashboard reports service and terminal-bridge readiness; it never exposes account information, credentials, or trading decisions.</p></div></div></div>
        <div class="badge"><span class="dot"></span>LIVE STATUS</div>
      </section>
      <section class="grid" aria-live="polite">
        <article class="card"><p class="label">CONTROL-PLANE HEALTH</p><p class="value" id="system-value">Checking…</p><p class="detail" id="system-detail">Fetching current service status.</p><span class="status" id="system-status">CONNECTING</span></article>
        <article class="card"><p class="label">MT5 BRIDGE CONNECTION</p><p class="value" id="mt5-value">Checking…</p><p class="detail" id="mt5-detail">Fetching terminal bridge capability.</p><span class="status warning" id="mt5-status">CONNECTING</span></article>
        <article class="card"><p class="label">UNIFIED ADAPTERS</p><p class="value" id="adapter-value">Checking…</p><p class="detail" id="adapter-detail">Loading supported platform boundaries.</p><span class="status warning" id="adapter-status">CONNECTING</span></article>
      </section>
      <div class="foot"><p id="updated">Last checked: —</p><p>Paper-first controls are active. <a href="/privacy">Privacy Policy</a> · <a href="/terms">Terms of Service</a> · <a href="/api/health">API health endpoint</a></p></div>
    </main>
    <script>
      const systemValue = document.getElementById('system-value'); const systemDetail = document.getElementById('system-detail'); const systemStatus = document.getElementById('system-status'); const mt5Value = document.getElementById('mt5-value'); const mt5Detail = document.getElementById('mt5-detail'); const mt5Status = document.getElementById('mt5-status'); const adapterValue = document.getElementById('adapter-value'); const adapterDetail = document.getElementById('adapter-detail'); const adapterStatus = document.getElementById('adapter-status'); const updated = document.getElementById('updated');
      function badge(element, label, tone) { element.textContent = label; element.className = 'status' + (tone ? ' ' + tone : ''); }
      async function refreshStatus() { try { const response = await fetch('/api/status', { cache:'no-store' }); if (!response.ok) throw new Error('Status request failed'); const data = await response.json(); const mt5 = data.mt5; const adapters = data.adapters || []; systemValue.textContent = data.status === 'healthy' ? 'System healthy' : 'System degraded'; systemDetail.textContent = 'Uptime ' + data.uptimeSeconds + ' seconds · API is responding'; badge(systemStatus, data.status.toUpperCase(), data.status === 'healthy' ? '' : 'warning'); mt5Value.textContent = mt5.state.replaceAll('_',' '); mt5Detail.textContent = mt5.capabilities.readAccount ? 'Account read access available' : 'No terminal bridge has been configured'; badge(mt5Status, mt5.state.replaceAll('_',' ').toUpperCase(), mt5.state === 'healthy' ? '' : 'warning'); adapterValue.textContent = adapters.length + ' adapters ready'; adapterDetail.textContent = adapters.map((adapter) => adapter.provider.replaceAll('_',' ')).join(' · '); badge(adapterStatus, 'PAPER-FIRST', 'warning'); updated.textContent = 'Last checked: ' + new Date(data.serverTime).toLocaleString(); } catch (error) { systemValue.textContent = 'Status unavailable'; systemDetail.textContent = 'The status endpoint did not respond.'; badge(systemStatus, 'UNAVAILABLE', 'error'); mt5Value.textContent = 'Unknown'; mt5Detail.textContent = 'Retrying automatically.'; badge(mt5Status, 'UNKNOWN', 'error'); adapterValue.textContent = 'Unavailable'; adapterDetail.textContent = 'Retrying automatically.'; badge(adapterStatus, 'UNKNOWN', 'error'); updated.textContent = 'Last checked: failed'; } }
      refreshStatus(); setInterval(refreshStatus, 30000);
    </script>
  </body>
</html>`;
}

type LegalSection = { heading: string; body: string };

function getLegalPage(title: string, summary: string, sections: LegalSection[]) {
  const content = sections
    .map((section) => `<section><h2>${section.heading}</h2>${section.body}</section>`)
    .join("");

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><meta name="theme-color" content="#081a2a" /><meta name="description" content="${summary}" /><title>${title} | AkiTrade</title><style>
:root{color-scheme:dark;--ink:#081a2a;--line:#274760;--text:#f5f8fc;--muted:#b7c5d3;--teal:#2dd4bf;--blue:#a9caff;--surface:rgba(17,52,81,.92)}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 85% 0%,#174878 0%,transparent 32%),var(--ink);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{width:min(860px,calc(100% - 40px));margin:0 auto;padding:48px 0 76px}.brand{display:inline-flex;align-items:center;gap:12px;color:var(--text);text-decoration:none;font-size:14px;font-weight:900;letter-spacing:.02em}.mark{display:grid;place-items:center;width:40px;height:40px;border-radius:13px;background:linear-gradient(145deg,#497df0,#285bb8);font-size:11px;letter-spacing:.1em}.eyebrow{margin:48px 0 8px;color:var(--teal);font-size:12px;font-weight:900;letter-spacing:.12em}h1{margin:0;max-width:740px;font-size:clamp(34px,7vw,56px);line-height:1.02;letter-spacing:-.05em}.lede{max-width:720px;margin:18px 0 0;color:var(--muted);font-size:17px;line-height:1.65}.updated{margin:22px 0 0;color:var(--muted);font-size:13px}article{margin-top:36px;padding:clamp(22px,5vw,42px);border:1px solid var(--line);border-radius:24px;background:var(--surface);box-shadow:0 22px 48px rgba(0,0,0,.18)}section+section{margin-top:32px;padding-top:32px;border-top:1px solid rgba(167,203,233,.16)}h2{margin:0;font-size:22px;line-height:1.2;letter-spacing:-.025em}p,li{color:var(--muted);font-size:15px;line-height:1.7}p{margin:14px 0 0}ul{margin:14px 0 0;padding-left:22px}strong{color:var(--text)}a{color:var(--blue);text-underline-offset:3px}.footer{display:flex;flex-wrap:wrap;gap:14px 20px;margin-top:24px;color:var(--muted);font-size:13px}@media(max-width:640px){main{width:min(100% - 28px,860px);padding-top:30px}.eyebrow{margin-top:36px}article{border-radius:20px}}</style></head><body><main><a class="brand" href="/"><span class="mark">AKI</span><span>AkiTrade</span></a><p class="eyebrow">EXNESS AUTO TRADER</p><h1>${title}</h1><p class="lede">${summary}</p><p class="updated">Last updated: August 22, 2026</p><article>${content}</article><nav class="footer" aria-label="Legal navigation"><a href="/">Control Plane</a><a href="/privacy">Privacy Policy</a><a href="/terms">Terms of Service</a><a href="/api/health">API Health</a></nav></main></body></html>`;
}

export function getAkiTradePrivacyPolicyPage() {
  return getLegalPage(
    "Privacy Policy",
    "This Privacy Policy explains how AkiTrade handles information for its secure, paper-first trading workspace.",
    [
      { heading: "1. Scope", body: "<p>This Privacy Policy explains how AkiTrade, also presented as <strong>Exness Auto Trader</strong>, handles personal information when you use the mobile application, secure backend, and this public control-plane website. The current product is a <strong>paper-first</strong> workspace for simulated trading workflows, risk controls, analytics, and account-link preparation.</p>" },
      { heading: "2. Information we process", body: "<p>We process only the information reasonably needed to operate and protect the service. Depending on the features you use, this may include:</p><ul><li><strong>Account and authentication data</strong>, such as a unique account identifier, display name, email address, and authentication-session information supplied by the sign-in provider.</li><li><strong>Workspace data</strong>, such as paper-trading settings, risk limits, simulated orders, positions, backtests, performance records, notification preferences, and audit events.</li><li><strong>Connection metadata</strong>, such as the platform you select, consent state, connection status, and technical error details. We do not request or store a broker password in the AkiTrade mobile application.</li><li><strong>Device and technical data</strong>, such as an optional push-notification token, app version, device/platform information, IP-derived security information, and logs needed to diagnose outages, misuse, or security incidents.</li></ul>" },
      { heading: "3. Google sign-in", body: "<p>If Google sign-in is enabled, AkiTrade uses the Google account information you authorize, such as your name, email address, and stable account identifier, to create and secure your AkiTrade account. We use this information only to provide authentication, account recovery, security, and service communications. We do not sell Google user data, use it for advertising, or access Google services beyond the scopes you explicitly approve.</p>" },
      { heading: "4. How we use and share information", body: "<p>We use information to provide and maintain the workspace, authenticate users, preserve user-selected settings, calculate simulated trading and risk-control results, send requested notifications, investigate security issues, enforce these Terms, comply with legal obligations, and improve reliability. AkiTrade is not currently configured to use your information to place live broker orders.</p><p>We may share information with providers that host the application, deliver authentication, provide infrastructure, or send notifications, but only as needed to provide the service and subject to confidentiality and security obligations. We may also disclose information when required by law, to protect rights and safety, or to investigate fraud or abuse. We do not sell personal information or share it for cross-context behavioral advertising.</p>" },
      { heading: "5. Retention, deletion, and security", body: "<p>We retain information for as long as needed to operate your workspace, meet legal and security obligations, resolve disputes, and enforce agreements. Authentication and audit records may be retained for a limited period after account closure where reasonably necessary for security or compliance. You may request access, correction, deletion, or a copy of your personal information through the project support channel at <a href=\"https://github.com/expoxtechinc/AkiTrade/issues\">AkiTrade support</a>; do not post passwords, access tokens, account numbers, or other sensitive information in a public request.</p><p>We use reasonable technical and organizational measures designed to protect information, including encrypted transport, server-side secret management, authenticated sessions, and audit logging. No method of transmission or storage is completely secure.</p>" },
      { heading: "6. International use, children, and changes", body: "<p>The service may be operated using infrastructure in locations other than your country. Where permitted, using AkiTrade means information may be processed in those locations with appropriate safeguards. AkiTrade is not directed to children and should not be used by anyone who is not legally able to enter into these Terms in their location.</p><p>We may update this Privacy Policy when the service or legal requirements change. The current version will always be posted at this address with its updated date.</p>" },
    ],
  );
}

export function getAkiTradeTermsPage() {
  return getLegalPage(
    "Terms of Service",
    "These Terms govern access to AkiTrade's secure, paper-first trading workspace and related services.",
    [
      { heading: "1. Acceptance and eligibility", body: "<p>These Terms of Service govern your access to AkiTrade, including the Exness Auto Trader mobile application, secure backend, and related services. By creating an account or using the service, you agree to these Terms and the <a href=\"/privacy\">Privacy Policy</a>. You must be legally able to enter into this agreement where you live and must comply with all laws and platform rules that apply to you.</p>" },
      { heading: "2. Current service and paper-first boundary", body: "<p>AkiTrade currently provides a paper-first workspace that can model strategies, simulated orders, risk limits, analytics, backtests, notifications, and account-link preparation. <strong>It does not provide live trade execution, brokerage services, custody, or investment management.</strong> Any future live integration would require separate release controls, an authorized official platform connection, appropriate disclosures, and your explicit action.</p>" },
      { heading: "3. No investment, legal, or tax advice", body: "<p>AkiTrade provides software tools and informational outputs only. It does not provide personalized investment, financial, legal, tax, or trading advice. AI-generated analysis is recommendation-only, may be incomplete or inaccurate, and is not an instruction to buy, sell, hold, or take any financial action. Simulated performance and backtests do not predict future results. You are solely responsible for evaluating any strategy, decision, or external transaction.</p>" },
      { heading: "4. Account security and acceptable use", body: "<p>You are responsible for the accuracy of information associated with your account, maintaining the confidentiality of your sign-in credentials, and all activity occurring through your account. You must not misuse the service, bypass access controls, interfere with its operation, reverse engineer it except where law permits, upload malicious code, use it unlawfully, or imply that AkiTrade guarantees a profit or a particular trading outcome.</p>" },
      { heading: "5. Platform connections and third parties", body: "<p>Where the service presents a platform connection, you must use only accounts and permissions you are authorized to use. You must not provide broker passwords to the AkiTrade mobile application. Trading platforms, brokers, exchanges, mobile stores, authentication providers, and other third parties have their own terms and policies, and AkiTrade is not responsible for their services, availability, data, conduct, or fees.</p>" },
      { heading: "6. Availability, intellectual property, and changes", body: "<p>We may change, suspend, or discontinue features to maintain security, comply with law, improve reliability, or evolve the service. We do not promise that the service will always be available, uninterrupted, accurate, or compatible with every device or third-party platform.</p><p>AkiTrade and its original software, design, content, and trademarks are protected by applicable intellectual-property laws. Subject to these Terms, we grant you a limited, personal, revocable, non-transferable right to use the service for its intended purpose.</p>" },
      { heading: "7. Disclaimers and limitation of liability", body: "<p>To the maximum extent permitted by law, the service is provided <strong>as is</strong> and <strong>as available</strong>, without warranties of merchantability, fitness for a particular purpose, non-infringement, availability, accuracy, or results. To the maximum extent permitted by law, AkiTrade will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for losses arising from market movements, trading decisions, third-party services, outages, lost data, or unauthorized access. Nothing in these Terms limits liability that cannot lawfully be limited.</p>" },
      { heading: "8. Suspension, termination, and contact", body: "<p>You may stop using the service at any time. We may suspend or terminate access where reasonably necessary to protect the service, users, or third parties; to investigate suspected misuse; or to comply with law. We may update these Terms by posting a revised version here. Continued use after the effective date of a revised version means you accept the updated Terms, to the extent permitted by law.</p><p>For questions about these Terms, use <a href=\"https://github.com/expoxtechinc/AkiTrade/issues\">AkiTrade support</a>. These Terms do not limit any mandatory consumer protections that apply in your country or region.</p>" },
    ],
  );
}
