import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { AkiTradeAuthGate } from "@/components/akitrade-auth-gate";
import { AkiTradeHeader } from "@/components/akitrade-header";
import { Card, formatMoney, Metric, PrimaryButton, SectionTitle, StatusPill } from "@/components/akitrade-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { haptic } from "@/lib/haptics";
import { trpc } from "@/lib/trpc";

const symbols = ["EURUSD", "GBPUSD", "USDJPY"] as const;

export default function BacktestScreen() { return <ScreenContainer className="px-5" containerClassName="bg-background"><AkiTradeAuthGate><BacktestContent /></AkiTradeAuthGate></ScreenContainer>; }
function BacktestContent() { const colors = useColors(); const [symbol, setSymbol] = useState<typeof symbols[number]>("EURUSD"); const run = trpc.trading.runBacktest.useMutation(); const result = run.data; return <ScrollView contentContainerStyle={styles.content}><AkiTradeHeader title="Paper backtest" subtitle="Deterministic simulation, not market data" /><Card style={styles.cardGap}><StatusPill label="SYNTHETIC PAPER DATA" tone="warning" /><Text style={[styles.note, { color: colors.muted }]}>This tool tests the saved paper strategy on deterministic synthetic candles. It does not use broker prices, execute any order, or estimate likely market returns.</Text><View style={styles.picker}>{symbols.map((candidate) => <Pressable key={candidate} onPress={() => setSymbol(candidate)} style={({ pressed }) => [styles.pickerButton, { borderColor: symbol === candidate ? colors.primary : colors.border, backgroundColor: symbol === candidate ? `${colors.primary}12` : colors.surface, opacity: pressed ? 0.7 : 1 }]}><Text style={[styles.pickerText, { color: symbol === candidate ? colors.primary : colors.foreground }]}>{candidate}</Text></Pressable>)}</View><PrimaryButton label={run.isPending ? "Running paper backtest…" : "Run paper backtest"} onPress={() => { haptic.light(); run.mutate({ symbol }, { onSuccess: () => haptic.success(), onError: () => haptic.error() }); }} disabled={run.isPending} /></Card>{result ? <><SectionTitle title="Latest result" /><Card style={styles.cardGap}><View style={styles.metricRow}><Metric label="Net P/L" value={formatMoney(result.metrics.netPnl)} tone={result.metrics.netPnl >= 0 ? "positive" : "negative"} /><Metric label="Trades" value={String(result.metrics.totalTrades)} /></View><View style={[styles.rule, { backgroundColor: colors.border }]} /><View style={styles.metricRow}><Metric label="Win rate" value={`${result.metrics.winRate}%`} /><Metric label="Max drawdown" value={formatMoney(-result.metrics.maxDrawdown)} tone="negative" /></View><Text style={[styles.note, { color: colors.muted }]}>{result.disclaimer}</Text></Card></> : null}<Text style={[styles.disclaimer, { color: colors.muted }]}>Backtest results are simulations and do not guarantee profitability or future performance.</Text></ScrollView>; }
const styles = StyleSheet.create({ content: { paddingBottom: 32 }, cardGap: { gap: 14 }, note: { fontSize: 13, lineHeight: 19 }, picker: { flexDirection: "row", gap: 8, flexWrap: "wrap" }, pickerButton: { minHeight: 38, justifyContent: "center", paddingHorizontal: 12, borderRadius: 11, borderWidth: 1 }, pickerText: { fontSize: 13, fontWeight: "900" }, metricRow: { flexDirection: "row", gap: 12 }, rule: { height: 1 }, disclaimer: { marginTop: 24, fontSize: 12, lineHeight: 18, textAlign: "center" } });
