import { ScrollView, StyleSheet, Text, View } from "react-native";

import { AkiTradeAuthGate } from "@/components/akitrade-auth-gate";
import { AkiTradeHeader } from "@/components/akitrade-header";
import { Card, EmptyState, LoadingState, SectionTitle, StatusPill } from "@/components/akitrade-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

export default function ConnectionScreen() { return <ScreenContainer className="px-5" containerClassName="bg-background"><AkiTradeAuthGate><ConnectionContent /></AkiTradeAuthGate></ScreenContainer>; }
function ConnectionContent() { const colors = useColors(); const bridge = trpc.trading.mt5BridgeHealth.useQuery(); if (bridge.isLoading) return <LoadingState label="Checking MT5 bridge contract…" />; if (!bridge.data) return <EmptyState title="Connection unavailable" detail="The secure bridge status could not be retrieved." />; const d = bridge.data; return <ScrollView contentContainerStyle={styles.content}><AkiTradeHeader title="Connection" subtitle="MT5-compatible integration boundary" /><Card style={styles.cardGap}><View style={styles.row}><View><Text style={[styles.title, { color: colors.foreground }]}>MT5 bridge</Text><Text style={[styles.note, { color: colors.muted }]}>A future server-hosted terminal-side adapter</Text></View><StatusPill label={d.state.replaceAll("_", " ").toUpperCase()} tone="warning" /></View><Text style={[styles.note, { color: colors.muted }]}>The mobile client does not connect directly to MT5. A future bridge must run beside a managed terminal, use securely stored backend credentials, and report normalized health information to AkiTrade.</Text></Card><SectionTitle title="Version-one capability" /><Card style={styles.cardGap}><Capability label="Read account and terminal data" value={d.capabilities.readAccount ? "Available" : "Not configured"} /><Capability label="Read positions" value={d.capabilities.readPositions ? "Available" : "Not configured"} /><Capability label="Execute live orders" value="Hard disabled" /></Card><SectionTitle title="Security boundary" /><Card><Text style={[styles.note, { color: colors.muted }]}>Exness passwords are never requested, stored, or transmitted by this application. Any API keys or future bridge credentials belong only in the secure backend environment. Paper automation remains independent of broker connectivity.</Text></Card></ScrollView>; }
function Capability({ label, value }: { label: string; value: string }) { const colors = useColors(); return <View style={styles.capability}><Text style={[styles.capabilityLabel, { color: colors.foreground }]}>{label}</Text><Text style={[styles.capabilityValue, { color: value === "Hard disabled" ? colors.success : colors.muted }]}>{value}</Text></View>; }
const styles = StyleSheet.create({ content: { paddingBottom: 32 }, cardGap: { gap: 14 }, row: { flexDirection: "row", justifyContent: "space-between", gap: 12 }, title: { fontSize: 17, fontWeight: "900" }, note: { marginTop: 3, fontSize: 13, lineHeight: 19 }, capability: { flexDirection: "row", justifyContent: "space-between", gap: 12 }, capabilityLabel: { flex: 1, fontSize: 14, fontWeight: "800" }, capabilityValue: { fontSize: 13, fontWeight: "800" } });
