import { ScrollView, StyleSheet, Text, View } from "react-native";

import { AkiTradeAuthGate } from "@/components/akitrade-auth-gate";
import { AkiTradeHeader } from "@/components/akitrade-header";
import { Card, EmptyState, formatMoney, LoadingState, Metric, SectionTitle, StatusPill } from "@/components/akitrade-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

export default function PerformanceScreen() { return <ScreenContainer className="px-5" containerClassName="bg-background"><AkiTradeAuthGate><PerformanceContent /></AkiTradeAuthGate></ScreenContainer>; }
function PerformanceContent() { const colors = useColors(); const performance = trpc.trading.performance.useQuery(); if (performance.isLoading) return <LoadingState label="Calculating paper performance…" />; if (!performance.data) return <EmptyState title="Performance unavailable" detail="The authenticated paper workspace did not return a performance summary." />; const d = performance.data; return <ScrollView contentContainerStyle={styles.content}><AkiTradeHeader title="Performance" subtitle="Closed paper positions only" /><Card style={styles.cardGap}><StatusPill label="SIMULATED RESULTS" tone="warning" /><View style={styles.metricRow}><Metric label="Net P/L" value={formatMoney(d.netPnl)} tone={d.netPnl >= 0 ? "positive" : "negative"} /><Metric label="Completed trades" value={String(d.completedTrades)} /></View><View style={[styles.rule, { backgroundColor: colors.border }]} /><View style={styles.metricRow}><Metric label="Win rate" value={`${d.winRate}%`} /><Metric label="Profit factor" value={String(d.profitFactor)} /></View></Card><SectionTitle title="Trade quality" /><Card><View style={styles.metricRow}><Metric label="Average win" value={formatMoney(d.averageWin)} tone="positive" /><Metric label="Average loss" value={formatMoney(d.averageLoss)} tone="negative" /></View></Card><SectionTitle title="Saved paper backtests" />{d.backtests.length === 0 ? <EmptyState title="No saved backtests" detail="Run a deterministic paper backtest from Strategy to retain its summary here." /> : <View style={styles.stack}>{d.backtests.map((backtest) => <Card key={backtest.id}><Text style={[styles.symbol, { color: colors.foreground }]}>{backtest.symbol}</Text><Text style={[styles.detail, { color: colors.muted }]}>Ending balance {formatMoney(Number(backtest.endingBalance))}</Text></Card>)}</View>}<Text style={[styles.disclaimer, { color: colors.muted }]}>Performance is derived from paper positions and deterministic backtests, not live account activity. It is not a forecast.</Text></ScrollView>; }
const styles = StyleSheet.create({ content: { paddingBottom: 32 }, cardGap: { gap: 14 }, metricRow: { flexDirection: "row", gap: 12 }, rule: { height: 1 }, stack: { gap: 9 }, symbol: { fontSize: 16, fontWeight: "900" }, detail: { marginTop: 3, fontSize: 12 }, disclaimer: { marginTop: 22, fontSize: 12, lineHeight: 18, textAlign: "center" } });
